# Bank exercise

In [1]:
import pandas as pd
import numpy as np
import sklearn as sk

## Es. 1

In [2]:
df = pd.read_csv('../data/bank.csv', sep=',')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
print('Shape', df.shape)
print('Righe', df.shape[0])
print('Colonne', df.shape[1])

Shape (10000, 14)
Righe 10000
Colonne 14

In [4]:
df.isnull().sum().sum()

np.int64(0)

In [5]:
total = df['Exited'].count()
num_exited = df['Exited'][df['Exited'] == 1].count()
num_not_exited = df['Exited'][df['Exited'] == 0].count()
total, num_exited, num_not_exited, num_exited/total*100, num_not_exited/total*100

(np.int64(10000),
 np.int64(2037),
 np.int64(7963),
 np.float64(20.369999999999997),
 np.float64(79.63))

Dataset not balanced with respect to the class to predict.

## Es. 2

In [6]:
# Execute once
df['Gender'] = df['Gender'].map({'Male': 0, 'Female': 1})
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,1,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,1,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,1,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,1,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,1,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,0,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,0,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,1,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,0,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,1,28,4,130142.79,1,1,0,38190.78,0

## Es. 3

In [7]:
oh_enc = sk.preprocessing.OneHotEncoder()

In [8]:
oh_enc.fit(df['Geography'].to_numpy().reshape(-1,1))

OneHotEncoder()

In [9]:
enc_data = oh_enc.transform(df['Geography'].to_numpy().reshape(-1,1)).toarray()
enc_data

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [10]:
cols = oh_enc.get_feature_names_out()
cols

array(['x0_France', 'x0_Germany', 'x0_Spain'], dtype=object)

In [11]:
df_geography_enc = pd.DataFrame(enc_data, columns=cols)

In [12]:
df = df.drop(columns=['Geography'], axis=1)
df

,RowNumber,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,1,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,1,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,1,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,1,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,1,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,0,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,0,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,1,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,0,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,1,28,4,130142.79,1,1,0,38190.78,0

In [13]:
df = pd.concat([df, df_geography_enc], axis=1)
df

,RowNumber,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,x0_France,x0_Germany,x0_Spain
0,1,15634602,Hargrave,619,1,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,2,15647311,Hill,608,1,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,3,15619304,Onio,502,1,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,4,15701354,Boni,699,1,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,5,15737888,Mitchell,850,1,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,0,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,9997,15569892,Johnstone,516,0,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,9998,15584532,Liu,709,1,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,9999,15682355,Sabbatini,772,0,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,10000,15628319,Walker,792,1,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

## Es. 4

These three columns must be removed:
- *RowNumber* and *CustomerId* must be removed to prevent overfitting;
- *Surname* both for overfitting and because it is something that really should not contribute to the prediction.

In [14]:
df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'])
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,x0_France,x0_Germany,x0_Spain
0,619,1,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,1,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,1,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,1,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,1,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,0,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,1,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,0,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,1,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [15]:
X = df.drop(columns=['Exited'])
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,x0_France,x0_Germany,x0_Spain
0,619,1,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,1,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,1,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,1,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,1,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,0,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,1,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,0,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0
9999,792,1,28,4,130142.79,1,1,0,38190.78,1.0,0.0,0.0

In [16]:
y = df[['Exited']]
y

      Exited
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 1 columns]

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=0)

In [18]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,x0_France,x0_Germany,x0_Spain
2967,579,1,39,5,117833.30,3,0,0,5831.00,0.0,1.0,0.0
700,750,1,32,5,0.00,2,1,0,95611.47,1.0,0.0,0.0
3481,729,1,34,9,53299.96,2,1,1,42855.97,0.0,0.0,1.0
1621,689,0,38,5,75075.14,1,1,1,8651.92,0.0,0.0,1.0
800,605,0,52,7,0.00,2,1,1,173952.50,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9225,594,1,32,4,120074.97,2,1,1,162961.79,0.0,1.0,0.0
4859,794,1,22,4,114440.24,1,1,1,107753.07,0.0,0.0,1.0
3264,738,0,35,5,161274.05,2,1,0,181429.87,1.0,0.0,0.0
9845,590,1,38,9,0.00,2,1,1,148750.16,0.0,0.0,1.0
2732,623,1,48,1,108076.33,1,1,0,118855.26,0.0,1.0,0.0

In [19]:
X_test

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,x0_France,x0_Germany,x0_Spain
9394,597,1,35,8,131101.04,1,1,1,192852.67,0.0,1.0,0.0
898,523,1,40,2,102967.41,1,1,0,128702.10,1.0,0.0,0.0
2398,706,1,42,8,95386.82,1,1,1,75732.25,0.0,0.0,1.0
5906,788,0,32,4,112079.58,1,0,0,89368.59,1.0,0.0,0.0
2343,706,0,38,5,163034.82,2,1,1,135662.17,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8764,773,0,51,8,116197.65,2,1,1,86701.40,0.0,1.0,0.0
4359,545,1,44,2,127536.44,1,1,0,108398.63,0.0,1.0,0.0
2041,840,1,39,1,94968.97,1,1,0,84487.62,1.0,0.0,0.0
1108,679,0,38,7,110555.37,2,1,0,46522.68,0.0,1.0,0.0
3332,735,0,31,3,119558.35,1,0,0,72927.68,1.0,0.0,0.0

In [20]:
y_train

      Exited
2967       1
700        0
3481       0
1621       1
800        0
...      ...
9225       0
4859       0
3264       0
9845       0
2732       1

[7500 rows x 1 columns]

In [21]:
y_test

      Exited
9394       0
898        1
2398       0
5906       0
2343       0
...      ...
8764       0
4359       0
2041       0
1108       0
3332       0

[2500 rows x 1 columns]

## Es. 5

In [22]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()

In [23]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [24]:
y_pred = dtc.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc*100}%')

Accuracy: 79.75999999999999%

## Es. 6

In [26]:
X_train['new_feature'] = (X_train['EstimatedSalary'] * X_train['Tenure'] + X_train['Balance']) / 2
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,x0_France,x0_Germany,x0_Spain,new_feature
2967,579,1,39,5,117833.30,3,0,0,5831.00,0.0,1.0,0.0,73494.150
700,750,1,32,5,0.00,2,1,0,95611.47,1.0,0.0,0.0,239028.675
3481,729,1,34,9,53299.96,2,1,1,42855.97,0.0,0.0,1.0,219501.845
1621,689,0,38,5,75075.14,1,1,1,8651.92,0.0,0.0,1.0,59167.370
800,605,0,52,7,0.00,2,1,1,173952.50,1.0,0.0,0.0,608833.750
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9225,594,1,32,4,120074.97,2,1,1,162961.79,0.0,1.0,0.0,385961.065
4859,794,1,22,4,114440.24,1,1,1,107753.07,0.0,0.0,1.0,272726.260
3264,738,0,35,5,161274.05,2,1,0,181429.87,1.0,0.0,0.0,534211.700
9845,590,1,38,9,0.00,2,1,1,148750.16,0.0,0.0,1.0,669375.720
2732,623,1,48,1,108076.33,1,1,0,118855.26,0.0,1.0,0.0,113465.795

In [27]:
X_test['new_feature'] = (X_test['EstimatedSalary'] * X_test['Tenure'] + X_test['Balance']) / 2
X_test

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,x0_France,x0_Germany,x0_Spain,new_feature
9394,597,1,35,8,131101.04,1,1,1,192852.67,0.0,1.0,0.0,836961.200
898,523,1,40,2,102967.41,1,1,0,128702.10,1.0,0.0,0.0,180185.805
2398,706,1,42,8,95386.82,1,1,1,75732.25,0.0,0.0,1.0,350622.410
5906,788,0,32,4,112079.58,1,0,0,89368.59,1.0,0.0,0.0,234776.970
2343,706,0,38,5,163034.82,2,1,1,135662.17,0.0,1.0,0.0,420672.835
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8764,773,0,51,8,116197.65,2,1,1,86701.40,0.0,1.0,0.0,404904.425
4359,545,1,44,2,127536.44,1,1,0,108398.63,0.0,1.0,0.0,172166.850
2041,840,1,39,1,94968.97,1,1,0,84487.62,1.0,0.0,0.0,89728.295
1108,679,0,38,7,110555.37,2,1,0,46522.68,0.0,1.0,0.0,218107.065
3332,735,0,31,3,119558.35,1,0,0,72927.68,1.0,0.0,0.0,169170.695

In [28]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [29]:
new_y_pred = dtc.predict(X_test)

In [30]:
new_acc = accuracy_score(y_test, new_y_pred)
print(f'Accuracy: {new_acc*100}%')

Accuracy: 79.47999999999999%

## Es. 7

In [31]:
from sklearn import preprocessing

In [32]:
stsc = preprocessing.StandardScaler()
scaler = stsc.fit(X_train)

In [33]:
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[-0.73550706,  1.08726059,  0.01526571, ...,  1.76021608,
        -0.57468161, -0.96255481],
       [ 1.02442719,  1.08726059, -0.65260917, ..., -0.56811207,
        -0.57468161, -0.22033229],
       [ 0.80829492,  1.08726059, -0.46178778, ..., -0.56811207,
         1.74009395, -0.30788655],
       ...,
       [ 0.90092304, -0.91974271, -0.36637708, ..., -0.56811207,
        -0.57468161,  1.10320725],
       [-0.62229491,  1.08726059, -0.08014499, ..., -0.56811207,
         1.74009395,  1.70925471],
       [-0.28265848,  1.08726059,  0.87396199, ...,  1.76021608,
        -0.57468161, -0.78333023]])

In [34]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-0.55025082,  1.08726059, -0.36637708, ...,  1.76021608,
        -0.57468161,  2.46067329],
       [-1.31185979,  1.08726059,  0.11067641, ..., -0.56811207,
        -0.57468161, -0.48417153],
       [ 0.57157862,  1.08726059,  0.3014978 , ..., -0.56811207,
         1.74009395,  0.2800309 ],
       ...,
       [ 1.95070838,  1.08726059,  0.01526571, ..., -0.56811207,
        -0.57468161, -0.88976426],
       [ 0.29369426, -0.91974271, -0.08014499, ...,  1.76021608,
        -0.57468161, -0.31414045],
       [ 0.870047  , -0.91974271, -0.74801987, ..., -0.56811207,
        -0.57468161, -0.533561  ]])

In [35]:
dtc.fit(X_train_scaled, y_train)

DecisionTreeClassifier()

In [36]:
y_pred = dtc.predict(X_test_scaled)

In [37]:
acc = accuracy_score(y_test, y_pred)
print(f'Accuracy: {acc*100}%')

Accuracy: 79.4%