1. Il file weather.csv contiene informazioni sul meteo di alcune città australiane. Caricare il suo contenuto in un dataframe.

   Quante righe e quante colonne ci sono nel dataset?

   Ci sono valori mancanti?

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('weather.csv', sep=';')
df

,Month,Location,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,1,Albury,20.4,37.6,0.0,54,0,7,46,17,1013.4,1009.2,3,26.1,36.7,No,No
1,1,Albury,20.9,33.6,0.4,50,9,17,54,30,1011.1,1008.4,8,24.8,31.7,No,Yes
2,1,Albury,18.4,23.1,2.2,48,11,39,62,67,1014.0,1014.8,8,21.8,19.5,Yes,Yes
3,1,Albury,17.3,23.7,15.6,39,9,17,74,65,1017.9,1016.5,8,19.2,21.6,Yes,Yes
4,1,Albury,15.5,22.9,6.8,31,6,9,92,63,1016.3,1013.9,8,17.2,22.2,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14463,12,Uluru,22.1,35.8,63.8,43,17,31,77,41,997.8,995.2,2,26.0,33.5,Yes,No
14464,12,Uluru,22.6,36.8,0.0,50,30,15,63,39,1000.0,998.8,-1,29.7,34.0,No,No
14465,12,Uluru,23.2,38.0,0.0,33,17,17,25,14,1004.4,1001.0,-1,28.7,36.4,No,No
14466,12,Uluru,19.7,37.0,0.0,37,22,6,30,23,1004.6,1000.9,-1,28.2,35.1,No,No
14467,12,Uluru,23.7,33.0,0.0,46,24,17,40,38,1005.1,1002.7,-1,30.1,31.5,No,No

In [3]:
df.shape[0] # righe

14468

In [4]:
df.shape[1] # colonne

17

In [5]:
df.isnull().sum()

Month            0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
WindGustSpeed    0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

2. Aggiungere al dataset:

- una nuova colonna "temp_diff" con la differenza in valore assoluto tra i valori di temperatura alle 9 del mattino e le 3 del pomeriggio

- una nuova colonna "hum_diff" con la differenza in valore assoluto tra i valori di umidità alle 9 del mattino e le 3 del pomeriggio

In [6]:
df['temp_diff'] = abs(df['Temp9am'] - df['Temp3pm'])
df['temp_diff']

0        10.6
1         6.9
2         2.3
3         2.4
4         5.0
         ...
14463     7.5
14464     4.3
14465     7.7
14466     6.9
14467     1.4
Name: temp_diff, Length: 14468, dtype: float64

In [7]:
df['hum_diff'] = abs(df['Humidity9am'] - df['Humidity3pm'])
df['hum_diff']

0        29
1        24
2         5
3         9
4        29
         ..
14463    36
14464    24
14465    11
14466     7
14467     2
Name: hum_diff, Length: 14468, dtype: int64

3. Selezionare soltanto le righe in cui "temp_diff" è maggiore di 10 e "hum_diff" è maggiore di 20. Qual è la location in cui si verifica più spesso questa elevata escursione termica (ovvero la location con il maggior numero di righe nella selezione)?

In [8]:
df[(df['temp_diff'] > 10) & (df['hum_diff'] > 20)].groupby('Location').count().sort_values('temp_diff', ascending=False)

,Month,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,temp_diff,hum_diff
Location,,,,,,,,,,,,,,,,,,
Richmond,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75
Tuggeranong,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69
Nhil,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69
Canberra,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
Mildura,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61
Albury,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54
BadgerysCreek,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51
Dartmoor,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47
Watsonia,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47,47
Woomera,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46
Bendigo,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43
Uluru,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
Sale,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28
Moree,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27
WaggaWagga,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
Nuriootpa,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
AliceSprings,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25
Ballarat,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
MountGambier,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
MelbourneAirport,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
Portland,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
Williamtown,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
Adelaide,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
PearceRAAF,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Melbourne,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
PerthAirport,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Perth,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Hobart,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Witchcliffe,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Cobar,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
NorahHead,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Sydney,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SydneyAirport,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Walpole,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Brisbane,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

4. Quante location sono presenti nel file?

In [9]:
df.groupby(['Location']).count().shape[0] # il count l'ho messo solo per far diventare un dataframe il risultato del groupby

42

In [10]:
# teacher's solution
print(df['Location'].nunique())
print(len(df['Location'].unique()))

42
42

5. Trasformare i valori della colonna "RainToday" convertendo "yes" in 1 e "no" in 0. Utilizzando il metodo groupby calcolare per ogni location il numero di giorni di pioggia.

In [11]:
df['RainToday'].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
mapping = {'Yes': 1, 'No': 0}
df['RainToday'].map(mapping)

0        0
1        0
2        1
3        1
4        1
        ..
14463    1
14464    0
14465    0
14466    0
14467    0
Name: RainToday, Length: 14468, dtype: int64

In [13]:
# esegui solo una volta
df['RainToday'] = df['RainToday'].map(mapping)

In [14]:
df.groupby('Location').sum().sort_values('RainToday', ascending=False)

,Month,MinTemp,MaxTemp,Rainfall,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow,temp_diff,hum_diff
Location,,,,,,,,,,,,,,,,,,
Portland,2340,3511.5,6432.2,1101.6,15858,6003,7706,27842,23650,365736.3,365345.8,1818,4738.8,5880.1,145,NoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoYesYesYes...,1241.1,5372
Walpole,2118,3714.4,6375.6,1200.2,13435,4659,5536,25282,22738,332634.4,332141.2,-327,4999.0,5736.8,130,NoNoNoNoNoNoYesNoNoNoNoNoYesYesYesYesNoNoNoNoN...,863.4,4038
Dartmoor,2382,3250.0,7090.2,867.6,14237,3961,6347,29989,22390,369891.5,369362.4,-364,4613.9,6528.3,126,NoNoNoNoNoNoNoNoYesNoNoYesNoNoNoNoNoNoYesNoNoN...,1976.2,8335
MountGambier,2209,3083.6,6748.5,790.2,15130,6219,7881,26812,21124,351725.4,351189.2,1887,4744.9,6150.4,123,NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesYes...,1486.7,7012
NorfolkIsland,1999,5663.8,7287.3,1320.5,13513,6340,6629,23666,23001,331689.5,331064.6,1622,6695.8,6809.6,122,NoYesNoYesYesYesNoNoYesNoNoNoNoNoNoNoNoYesYesN...,232.2,2047
Witchcliffe,2275,3694.3,7170.3,1202.4,14203,4983,6782,24696,20648,351232.5,350669.9,-345,5561.1,6497.0,119,NoNoNoNoNoNoNoNoYesNoNoNoNoNoYesNoNoNoNoNoNoYe...,1050.3,5280
Ballarat,2347,2810.7,6465.5,720.2,16739,7440,8590,30417,22278,363862.2,363304.3,1636,4172.0,5945.2,110,NoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoYesYesYesYesN...,1834.6,8579
MelbourneAirport,2384,3785.5,7479.2,614.6,17669,7589,8596,25772,19175,372023.2,371385.6,2016,5234.7,6886.9,96,NoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoYesNoNoYe...,1753.8,7337
Darwin,2360,8802.0,12103.8,1264.8,14431,4918,7304,25495,19420,368442.6,367132.6,1447,10270.5,11577.5,95,NoNoNoNoNoNoNoYesNoYesNoNoNoYesNoYesNoNoNoYesY...,1422.0,6543
Hobart,2366,3520.2,6555.2,689.6,17931,6136,7440,23376,18575,365456.8,364839.0,1862,4700.0,5999.6,94,NoNoNoNoNoNoNoNoYesNoYesNoNoNoNoNoNoNoNoNoNoNo...,1388.8,5591
Watsonia,2225,3676.8,7198.4,687.6,13587,3572,5363,27394,19344,353778.6,353120.4,1920,4849.7,6675.3,91,NoNoNoNoNoNoNoNoYesNoYesNoNoNoNoNoNoNoYesYesNo...,1913.4,8902
Perth,2383,4605.6,8801.6,715.8,12937,3881,5283,23296,17947,371479.8,370628.3,1294,6629.7,8216.7,91,NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoY...,1669.0,6101
Adelaide,2384,4518.9,8368.1,820.8,12750,3153,5055,22427,17213,372395.3,371684.6,-366,6167.8,7858.2,90,NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesYes...,1759.6,6216
Bendigo,2378,3382.7,7723.4,676.8,14342,4639,6342,25990,17836,367990.9,367246.5,1202,5022.1,7202.9,90,NoNoYesYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoN...,2206.0,8442
Nuriootpa,2338,3327.4,7716.5,678.8,15184,5392,6881,24443,16923,364246.4,363488.1,-18,5303.9,7205.0,89,NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoN...,1942.1,8334
Albury,2384,3746.0,8320.7,805.0,12516,3167,5615,27298,18032,372291.6,371397.5,1023,5467.5,7806.9,88,NoYesYesYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoY...,2407.2,9592
Cairns,1724,6432.6,8827.6,1308.8,11035,4659,6182,21366,19031,299303.8,298393.7,913,7774.5,8409.9,88,YesNoNoNoNoNoNoNoYesNoNoNoNoNoYesYesYesNoNoNoN...,672.6,2981
WaggaWagga,2208,3613.6,7895.1,736.6,12980,4626,5903,24271,15644,355111.2,354256.1,1324,5289.0,7457.6,86,YesNoNoYesYesNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNo...,2205.8,9033
Tuggeranong,2310,2754.5,7339.3,841.0,12553,2556,5266,25926,16703,358117.1,357130.4,-352,4556.2,6893.7,84,NoNoYesYesYesNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoYe...,2365.9,9551
SydneyAirport,2363,5569.2,8759.7,1265.2,17118,6709,9204,22577,18716,369217.7,368307.7,1534,6937.6,8138.6,84,NoNoYesYesYesYesNoNoNoNoNoNoNoYesYesNoNoNoNoNo...,1271.2,5107
Sydney,2302,5367.6,8303.7,1309.8,14502,5290,6797,22218,17982,355014.0,353126.1,1465,6454.4,7751.3,83,NoNoYesYesYesYesNoNoNoNoNoYesYesNoNoNoNoNoYesY...,1338.7,4892
NorahHead,2374,5702.0,8485.4,1029.6,14704,4681,7250,27060,24103,369200.0,368328.5,-363,6879.4,7806.1,82,NoNoYesYesYesYesNoNoYesNoNoYesYesYesYesNoNoNoY...,995.3,4021
Canberra,2262,2646.3,7479.0,777.6,14847,4180,7397,26451,17155,361278.1,360318.0,947,4650.3,6963.3,81,NoNoYesYesYesNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoYe...,2354.6,9550
CoffsHarbour,2231,4944.2,8506.9,1065.1,13521,5103,7461,23093,21204,351205.1,350335.4,659,7118.2,7943.9,80,NoNoYesNoYesNoNoNoNoNoNoNoNoNoYesYesNoNoNoNoNo...,902.7,3711
PerthAirport,2372,4364.7,8845.1,660.4,16059,6350,7974,21759,15843,369454.7,368552.3,1287,6576.8,8333.0,79,YesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNo...,1827.2,6660
Melbourne,2082,2524.5,4462.0,458.4,9348,2914,3717,17403,14113,248825.1,248397.7,1392,3257.3,4100.9,79,NoNoNoNoNoNoYesNoYesNoNoNoNoNoNoNoNoNoYesNoNoY...,932.0,3952
PearceRAAF,2306,4145.4,8847.1,707.8,15243,5619,7308,22966,16966,360192.6,359316.8,807,6465.4,8237.6,77,NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoYesNoNoNo...,1850.0,6620
Brisbane,2333,6035.2,9662.9,726.4,9911,2374,3879,21742,18487,361415.6,360267.8,1314,7983.4,9027.7,75,NoNoYesYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoYes...,1104.5,4083
Nhil,2380,3355.0,7982.5,469.4,15754,6099,7757,27040,17360,370102.6,369325.6,-364,4844.5,7440.0,74,NoNoYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesNoYesY...,2621.3,10080
Sale,2212,3038.7,6723.7,567.4,14330,4837,7493,26695,19666,337450.9,336802.3,1136,4575.9,6244.4,73,YesYesYesYesNoNoNoNoNoYesNoNoNoNoYesNoYesNoYes...,1735.5,7393
Williamtown,1747,3855.0,7174.3,1024.5,12654,5348,6597,21112,15789,305435.3,304655.3,781,5418.6,6776.7,70,NoNoYesYesYesYesNoNoNoNoNoYesYesYesYesNoNoNoYe...,1402.5,5785
Wollongong,2359,5539.8,8006.3,1267.2,16416,5868,7649,23586,22828,369152.5,368332.0,1007,6782.8,7433.8,68,NoNoYesYesYesYesNoNoNoNoNoNoNoYesYesNoNoNoNoNo...,798.4,3492
GoldCoast,2046,5329.8,7908.5,748.8,12266,5607,7697,20755,19768,311466.0,310631.2,-306,6892.9,7305.8,65,YesYesYesNoNoNoNoNoNoNoNoNoNoNoNoYesYesNoYesYe...,577.1,2839
Richmond,2362,4228.9,9091.2,802.2,12892,3207,5763,27015,17010,366269.3,365117.2,644,6165.7,8571.6,61,NoNoYesYesYesYesNoNoNoNoNoNoNoYesYesYesNoNoNoN...,2430.5,10183
BadgerysCreek,2145,3805.0,8452.7,664.6,11394,2481,4734,26578,17236,348993.3,347981.3,-343,5791.2,7914.1,57,NoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoYesYesYesNo...,2145.3,9554
Townsville,2246,7591.3,10591.2,939.6,13371,5305,8530,22689,20406,357364.2,356199.8,835,9279.0,10022.9,54,NoYesYesNoNoNoNoNoYesNoNoNoNoNoNoNoYesNoNoNoNo...,773.7,3029
Cobar,1282,3350.9,6289.4,498.6,9012,3789,3862,16045,10848,264769.6,264092.5,818,4477.0,6002.5,48,NoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoYesNoYesNoNoN...,1551.3,5373
Mildura,2379,4053.8,9047.1,358.6,13912,5164,6203,23777,13696,371385.2,370475.0,1304,5742.8,8520.6,46,NoNoYesYesNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoYesY...,2810.8,10457
Moree,2093,4206.7,8501.2,437.8,12579,5979,5381,19535,11782,317645.1,316619.3,767,6000.7,8065.0,45,YesNoNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoNo...,2111.5,8143
AliceSprings,2286,4859.9,10466.2,356.2,14142,5427,6222,15360,9387,361896.3,360547.9,892,7626.8,9971.7,39,NoNoNoNoNoNoNoNoNoNoNoYesYesNoNoNoNoNoYesYesNo...,2356.3,6309
Uluru,2270,4854.1,9855.6,472.4,13143,5670,5556,15394,9126,337408.2,336189.1,498,6857.2,9423.6,37,NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNo...,2569.6,6514
Woomera,2238,4626.6,9253.3,226.2,16001,7363,7876,19785,10460,359295.2,358366.6,456,6164.8,8773.1,31,NoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNoNo...,2608.7,9529

6. Creare una tabella pivot in cui per ogni location (sulle righe) e per ogni mese (sulle colonne) sia calcolata la temperatura massima media.

7. Visualizzare in un unico grafico la distribuzione dei valori di temperatura massima nel mese di maggio (5) e dicembre (12).

8. Visualizzare in uno scatterplot la relazione tra i valori di pressione e i valori di umidità (fare 2 plot distinti nella stessa figura, uno per i valori 9am e un altro per i valori 3pm). Colorare i punti di due colori diversi in base ai valori di RainToday.